/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "'Plus Jakarta Sans'",
          "'Inter'",
          "'Noto Sans Kannada'",
          "'Noto Sans Devanagari'",
          "system-ui",
          "sans-serif",
        ],
        display: [
          "'Plus Jakarta Sans'",
          "'Noto Sans Kannada'",
          "'Noto Sans Devanagari'",
          "system-ui",
          "sans-serif",
        ],
        body: [
          "'Inter'",
          "'Noto Sans Kannada'",
          "'Noto Sans Devanagari'",
          "system-ui",
          "sans-serif",
        ],
        kn: ["'Noto Sans Kannada'", "'Plus Jakarta Sans'", "sans-serif"],
        hi: ["'Noto Sans Devanagari'", "'Plus Jakarta Sans'", "sans-serif"],
      },
      colors: {
        nearvia: {
          canvas: "#FAFAF9",
          charcoal: "#0F172A",
          ink: "#1E293B",
          surface: "#FFFFFF",
          surface2: "#F1F5F9",
          surface3: "#E2E8F0",
          border: "#E2E8F0",
          borderHover: "#CBD5E1",
          cobalt: "#2563EB",
          cobaltHover: "#1D4ED8",
          tangerine: "#EA580C",
          tangerineHover: "#C2410C",
          emerald: "#16A34A",
          emeraldLight: "#DCFCE7",
          amber: "#D97706",
          amberLight: "#FEF3C7",
          rose: "#E11D48",
          roseLight: "#FFE4E6",
          teal: "#0D9488",
        },
      },
      boxShadow: {
        soft: "0 2px 10px -2px rgba(15, 23, 42, 0.06), 0 1px 3px 0 rgba(15, 23, 42, 0.04)",
        card: "0 4px 20px -2px rgba(15, 23, 42, 0.08), 0 2px 6px -1px rgba(15, 23, 42, 0.04)",
        hover: "0 12px 30px -4px rgba(15, 23, 42, 0.12), 0 4px 10px -2px rgba(15, 23, 42, 0.06)",
        float: "0 20px 40px -8px rgba(15, 23, 42, 0.18)",
      },
      borderRadius: {
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
      },
    },
  },
  plugins: [],
};
