/**
 * Standard Application Error Codes and Messages
 */

export enum ErrorCode {
  // Authentication & Authorization (1000 - 1099)
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  INVALID_TOKEN = "INVALID_TOKEN",

  // Validation & Input (2000 - 2099)
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_COORDINATES = "INVALID_COORDINATES",
  LOCATION_REQUIRED = "LOCATION_REQUIRED",
  RADIUS_EXCEEDED = "RADIUS_EXCEEDED",
  INVALID_DATE_RANGE = "INVALID_DATE_RANGE",

  // Resource Management & Work Execution (3000 - 3099)
  NOT_FOUND = "NOT_FOUND",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  CONFLICT = "CONFLICT",
  APPLICATION_DUPLICATE = "APPLICATION_DUPLICATE",
  APPLICATION_NOT_FOUND = "APPLICATION_NOT_FOUND",
  APPLICATION_INVALID_STATE = "APPLICATION_INVALID_STATE",
  WORK_ALREADY_FILLED = "WORK_ALREADY_FILLED",
  WORK_EXPIRED_OR_CANCELLED = "WORK_EXPIRED_OR_CANCELLED",
  ASSIGNMENT_NOT_FOUND = "ASSIGNMENT_NOT_FOUND",
  ASSIGNMENT_INVALID_STATE = "ASSIGNMENT_INVALID_STATE",
  CHECK_IN_WINDOW_CLOSED = "CHECK_IN_WINDOW_CLOSED",
  CHECK_IN_PROXIMITY_EXCEEDED = "CHECK_IN_PROXIMITY_EXCEEDED",
  ALREADY_CHECKED_IN = "ALREADY_CHECKED_IN",
  ALREADY_COMPLETED = "ALREADY_COMPLETED",
  NO_SHOW_NOT_ELIGIBLE = "NO_SHOW_NOT_ELIGIBLE",
  NOT_AUTHORIZED_FOR_ACTION = "NOT_AUTHORIZED_FOR_ACTION",
  INVALID_JOB_PIN = "INVALID_JOB_PIN",
  JOB_PIN_MAX_ATTEMPTS_EXCEEDED = "JOB_PIN_MAX_ATTEMPTS_EXCEEDED",
  CHECK_OUT_INVALID_STATE = "CHECK_OUT_INVALID_STATE",
  EVIDENCE_UPLOAD_FAILED = "EVIDENCE_UPLOAD_FAILED",

  // Payment Operations & Settlement (4000 - 4099)
  PAYMENT_ALREADY_CONFIRMED = "PAYMENT_ALREADY_CONFIRMED",
  PAYMENT_NOT_ELIGIBLE = "PAYMENT_NOT_ELIGIBLE",
  INVALID_PAYMENT_PIN = "INVALID_PAYMENT_PIN",
  PAYMENT_PIN_MAX_ATTEMPTS_EXCEEDED = "PAYMENT_PIN_MAX_ATTEMPTS_EXCEEDED",
  PAYMENT_AMOUNT_MISMATCH = "PAYMENT_AMOUNT_MISMATCH",
  PAYMENT_DISPUTED = "PAYMENT_DISPUTED",
  UNAUTHORIZED_PAYMENT_ACTION = "UNAUTHORIZED_PAYMENT_ACTION",

  // Intelligence & Natural Language Processing (6000 - 6099)
  NL_PARSE_FAILED = "NL_PARSE_FAILED",
  VOICE_PROCESSING_FAILED = "VOICE_PROCESSING_FAILED",
  INSUFFICIENT_MARKET_DATA = "INSUFFICIENT_MARKET_DATA",

  // System & Database (5000 - 5099)
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  DATABASE_ERROR = "DATABASE_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  RATE_LIMITED = "RATE_LIMITED",
  EXTERNAL_GATEWAY_ERROR = "EXTERNAL_GATEWAY_ERROR",
}

export interface ApiErrorResponse {
  success: false;
  error: {
    code: ErrorCode | string;
    message: string;
    details?: unknown;
    timestamp: string;
  };
}

export interface ApiSuccessResponse<T = unknown> {
  success: true;
  data: T;
  meta?: {
    page?: number;
    limit?: number;
    total?: number;
    totalPages?: number;
    searchCenter?: unknown;
    radiusKm?: number;
    timestamp?: string;
  };
}

export type ApiResponse<T = unknown> = ApiSuccessResponse<T> | ApiErrorResponse;
